services:
  - type: web
    name: beautynomy-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
