services:
  - type: web
    name: beautynomy-api
    env: node
    plan: free
    rootDir: Beautynomy/server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
